<?php

########################################################################
# Extension Manager/Repository config file for ext: "aoe_ipauth"
#
# Auto generated by Extension Builder 2014-01-16
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'IP Authentication',
	'description' => 'Authenticates users based on IP address settings',
	'category' => 'services',
	'author' => 'DEV',
	'author_email' => 'dev@aoe.com',
	'author_company' => 'AOE GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1dev',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.4',
			'fluid' => '1.4',
			'typo3' => '4.6',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>